oferta_homepage:
    path:     /hello/{name}
    defaults: { _controller: OfertaBundle:Default:index }

tipo_navegador:
    path:     /navegador
    defaults: { _controller: OfertaBundle:Default:tipoNavegador }
