ciudad_homepage:
    path:     /hello/{name}
    defaults: { _controller: CiudadBundle:Default:index }

ciudad_cambiar:
    pattern:  /ciudad/cambiar-a-{ciudad}
    defaults: { _controller: CiudadBundle:Default:cambiar }
    requirements:
        ciudad: .+
# Con .+ le indicamos que el nombre de ciudad puede contener cualquier carácter

ciudad_recientes:
    path: /{ciudad}/recientes
    defaults: { _controller: CiudadBundle:Default:recientes }

