usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /


tienda:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /

ciudad:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

oferta:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /

pagina_estatica:
    path:   /sitio/{pagina}/
    defaults: { _controller:OfertaBundle:Sitio:estatica }

# Ruta completa de la portada (con el slug de la ciudad)
portada:
    path:   /
    defaults: { _controller:OfertaBundle:Default:portada }

# Ruta simple de la portada
_portada:
    path:  /{ciudad}
    defaults: { _controller:OfertaBundle:Default:portada }
