usuario:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /


tienda:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /

ciudad:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /

oferta:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /

pagina_estatica:
    path:   /sitio/{pagina}/
    defaults: { _controller:OfertaBundle:Sitio:estatica }

# Ruta completa de la portada (con el slug de la ciudad)
#_portada:
#    path:   /
#    defaults: { _controller:FrameworkBundle:Redirect:redirect,
#                route: portada, ciudad: '%cupon.ciudad_por_defecto%' }

#_portada: # Cuando se quiere mandar a una url normalmente externa.
#    pattern: /
#    defaults:
#        _controller: FrameworkBundle:Redirect:urlRedirect
#        route: portada
#        path: /{ciudad: '%cupon.ciudad_por_defecto%'} #Por ejemplo: google.es

_portada: #el pattern es muy importante para que funcione
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: portada
        ciudad: 'barcelona'
        permanent: true

# Ruta simple de la portada
portada:
    path:  /{ciudad}
    defaults: { _controller: OfertaBundle:Default:portada, ciudad: null }

#prueba:
#    path:  /{ciudad}/{ruta_foto}
#    defaults: { _controller: OfertaBundle:Default:prueba }


