security:

    firewalls:
        frontend:
            pattern:      ^/*
            anonymous:    ~
            form_login:
                login_path: /usuario/login # o indicar el nombre de la ruta: usuario_login
                check_path: /usuario/login_check # o poner: usuario_login_check
                default_target_path:  /usuario/compras
# Redirigir el usuario a esta ruta despues de loguearse

# Para mantener la sesión abierta durante 3600 segundos
            remember_me:
                key:      cupon1234
                lifetime: 3600

    access_control:
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/*, roles: ROLE_USUARIO }

    providers:
        usuarios:
            entity: { class: Cupon\UsuarioBundle\Entity\Usuario, property: email }
    encoders:
        Cupon\UsuarioBundle\Entity\Usuario: plaintext
        #{ algorithm: sha512, iterations: 10}

