
# ruta de compras del usuario
usuario_compras:
    path: /compras
    defaults: { _controller: UsuarioBundle:Default:compras }

# Configuración de rutas para usuario
usuario_login:
    path:   /login
    defaults: { _controller: UsuarioBundle:Default:login }

usuario_login_check:
    path:   /login_check

usuario_logout:
    path:   /logout

# testeo del functionamiento de accesores de ultimaConexion campo añadido despues de tener las tablas llenas
usuario_testConexion:
    path:   /testConexion
    defaults: { _controller: UsuarioBundle:Default:testConexion }

# la ruta para poder registrar el usuario
usuario_registro:
    path: /registro
    defaults: { _controller: UsuarioBundle:Default:registro }

usuario_perfil:
    path: /perfil
    defaults: { _controller: UsuarioBundle:Default:perfil }